var mongoose = require('mongoose');

module.exports = mongoose.model('Project', {
  projectId: { type: String, index: { unique: true , required: true }},
  version: { type: String, required: true },
  name: { type: String, required: true },
  subname: { type: String },
  label: { type: String },
  campaign_duration: { type: Number, required: true },
  key_points: { type: String },
  project_duration: { type: Number, required: true },
  image: { type: String, required: true },
  preview: { type: String, required: true },
  status: { type: String, required: true },
  balance: { type: Number, required: true },
  progress: { type: Number, required: true },
  campaign_start: { type: Date, default: null },
  house: {
    description: { type: String, required: true },
    address: { type: String, required: true },
    location: { type: {lat: Number, lon: Number}, required: true },
    size: { type: Number, required: true },
    rooms: { type: Number, required: true },
    wc: { type: Number, required: true },
    status: { type: String, required: true },
    type: { type: String, required: true },
    price_per_meter: { type: Number, required: true },
    photos: { type: [{file: String}], default: [] }
  },
  finances: {
    description: { type: String, required: true },
    profitability: {type: Number, required: true },
    sell_enabled: { type: Boolean, required: true },
    rent_enabled: { type: Boolean, required: true },
    purchase: {
      price: { type: Number, required: true },
      taxes: { type: Number, required: true },
      refurbishment: { type: Number, required: true },
      unforeseen: { type: Number, required: true },
      total_price: { type: Number, required: true }
    },
    sell: {
      price: Number,
      profitability: Number,
      fee: Number,
      fee_nominal: Number,
      value_added_tax: Number,
      value_added_tax_nominal: Number,
      net_profitability: Number,
      corporate_tax: Number,
      corporate_tax_nominal: Number,
      corporate_profit: Number,
      management_fee: Number,
      management_fee_nominal: Number,
      developer_fee: Number,
      developer_fee_nominal: Number,
      platform_profit: Number,
      investor_profitability: Number
    },
    rent: {
      payment: Number,
      profitability: Number,
      insurance: Number,
      home_insurance: Number,
      ibi: Number,
      community_expenses: Number,
      unforeseen: Number,
      earnings: Number,
      net_profitability: Number,
      amortization: Number,
      corporate_tax: Number,
      corporate_tax_nominal: Number,
      corporate_profit: Number,
      platform_fee: Number,
      platform_profit: Number,
      investor_profitability: Number,
      profitability: Number,
    }
  },
  documents: { type: [{text: String, filename: String, filesize: String}], default: [] }
});
